### ISSUE TITLE
teipublisher behind proxy

### ISSUE THREAD

**Issue by eduarddrenth** [eeditiones/tei-publisher-app#74]
When running teipublisher behind a proxy like so:

```
ProxyPass "/jurisprudentia-frisica" "http://<host>:<port>/exist/apps/tei-publisher"
ProxyPassReverse "/jurisprudentia-frisica" "http://<host>:<port>/exist/apps/tei-publisher"
```

Several request fail because request are made to absolute url's (/exist/apps/...).

Can teipublisher be configured to use url's relative to /exist/apps/tei-publisher?

**Comment by eduarddrenth** [comment]
The filter block not being shown isn't related to the login problem I think. /jurisprudentia-frisica/api/search/facets?language=en-US&sort=title simply returns nothing, status 200

**Comment by eduarddrenth** [comment]
tomorrow I'll do some more testing in order to try and pinpoint problems more exact

**Comment by eduarddrenth** [comment]
For us this is a blocker, we don't want to run exist on a separate domain for every project. Anyone else who wants to run several teipublisher instances on different context root?

**Comment by eduarddrenth** [comment]
Acually I don't quite understand this issue... teipublisher is a servlet right?

Then it should be agnostic about it's contextpath, it shouldn't have to be configured at all, because the servlet container is responsible for providing the contextpath.

**Comment by wolfgangmm** [comment]
I don't know apache proxy too well, but I recently prepared a docker compose with nginx, which you may want to have a look at: https://github.com/eeditiones/teipublisher-docker-compose. The [nginx config](https://github.com/eeditiones/teipublisher-docker-compose/blob/master/conf/default.conf) maps `/exist/apps/tei-publisher` to `/` and `/exist/apps/eXide` to `/apps/eXide`.

I managed to change this to map `/publisher` to `/exist/apps/tei-publisher` instead by using a rewrite:

```
location /publisher {
    rewrite  ^  $request_uri; # get original URI
    rewrite  ^/publisher(/.*)$  /exist/apps/tei-publisher$1  break; # rewrite /publisher
    proxy_pass http://docker-publisher$uri;
```

You would still need to set `$config:context-path` to the corresponding root of the app, i.e. `/edition1`, because this is used to resolve absolute links within the app (my docker compose sets this via an environment variable - which is a feature I just added to the development branch of publisher I'm currently working at).

What I could not get to work yet: redirect `/publisher/` to `/publisher/index.html`.

**Comment by eduarddrenth** [comment]
I have no experience with nginx and we standardize on apache. The docker (compose/Dockerfile) setup also deviates from our approach based on exist-db docker hub image.

For now I will offer users a direct access without proxy.

Still it feels like the application is requesting url's it shouldn't and this problem shouldn't be solved in the proxy but in the application. Unfortunately trying to solve this would cost me too much time and effort, but perhaps I'll dive into it.

Also I discoverd that $config:context-path isn't a servlet context-path (which I would expect) but rather an application-path such as "/jurisprudentia-frisica/apps/tei-publisher".

**Comment by ntaliakouras** [comment]
Hello!

I think that I have such a problem using apache2.
Despite configuring apache proxy pass as said above and i can view my app, the problem is that I take the message "the server did not return any content" when trying to access a specific file.
The link to the file in the collection view is correct .
If I take the url, eg example.com/exist/apps/test/testcollection/testfile.xml and replace "example.com" with "localhost:8080" on the server everything is ok.

Any ideas about this?

Thank you in advance!

**Comment by eduarddrenth** [comment]
See e-editions in slack, I thought to have virtual hosting as a working alternative, but alas, retrieving documents fails. I am really stuck now....

**Comment by eduarddrenth** [comment]
Forgot about https://faq.teipublisher.com/general/proxy/, running in a virhost works!

**Comment by tuurma** [comment]
Another approach for setting the context path dynamically proposed by @windauer (to be put in `modules/config.xqm`) 

```xquery
declare variable $config:context-path :=
   if (not(empty(request:get-header("X-Forwarded-Host")))) then 
        ("") 
    else 
        (request:get-context-path() || substring-after($config:app-root, "/db"))
;

```

**Comment by eduarddrenth** [comment]
Thanks, perhaps I'll look into this option, but virhost is fine for us now
